spring.application.name=Shop

# Database connection prop
spring.datasource.url=jdbc:postgresql://localhost:5432/shopDB
spring.datasource.username=postgres
spring.datasource.password=postgres

#JPA prop
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Mail prop
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# adaugati emailul personal
spring.mail.username=gavrilita.rolland@gmail.com

# generati o parola din contul vostru-> security -> 2-step verification -> App passwords generati una noua pe care sa o folositi
# sau https://myaccount.google.com/apppasswords
spring.mail.password=dgim vnir qaas cuqr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

